spring:
  servlet:
      multipart:
        max-file-size: 10MB        # 단일 파일 최대 크기
        max-request-size: 10MB     # 요청당 최대 파일 크기
  
  application:
    name: shoppingmall

  mvc:
    view:
      prefix: "/WEB-INF/views"
      suffix: ".jsp"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shoppingmall
    username: shop_admin
    password: slsnrnsep5748

  devtools:
    livereload:
      enabled: true

  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true

server:
  port: 8080

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    jsp:
      init-parameters:
        development: true
    
  error:
    whitelabel:
      enabled: false
  
mybatis:
  type-aliases-package: com.shoppingmall.demo.domain
  mapper-locations: mapper/**/*.xml

logging:
  config: classpath:logback-spring.xml

custom:
  file:
    upload:
      path: src/main/resources/static/upload/product